// List of countries
export const countries = [
  { value: "us", label: "United States" },
  { value: "ca", label: "Canada" },
  { value: "uk", label: "United Kingdom" },
  { value: "au", label: "Australia" },
  { value: "de", label: "Germany" },
  { value: "fr", label: "France" },
  { value: "jp", label: "Japan" },
  { value: "cn", label: "China" },
  { value: "in", label: "India" },
  { value: "br", label: "Brazil" },
  { value: "mx", label: "Mexico" },
  { value: "es", label: "Spain" },
  { value: "it", label: "Italy" },
  { value: "nl", label: "Netherlands" },
  { value: "sg", label: "Singapore" },
  { value: "kr", label: "South Korea" },
  { value: "za", label: "South Africa" },
  { value: "ru", label: "Russia" },
  { value: "se", label: "Sweden" },
  { value: "ch", label: "Switzerland" },
  { value: "no", label: "Norway" },
  { value: "nz", label: "New Zealand" },
  { value: "ar", label: "Argentina" },
  { value: "cl", label: "Chile" },
  { value: "co", label: "Colombia" },
  { value: "pe", label: "Peru" },
  { value: "id", label: "Indonesia" },
  { value: "my", label: "Malaysia" },
  { value: "ph", label: "Philippines" },
  { value: "th", label: "Thailand" },
  { value: "vn", label: "Vietnam" },
  { value: "ae", label: "United Arab Emirates" },
  { value: "sa", label: "Saudi Arabia" },
  { value: "eg", label: "Egypt" },
  { value: "ng", label: "Nigeria" },
  { value: "ke", label: "Kenya" },
  { value: "gh", label: "Ghana" },
  { value: "other", label: "Other" },
]

// States/provinces by country
const states: Record<string, Array<{ value: string; label: string }>> = {
  us: [
    { value: "al", label: "Alabama" },
    { value: "ak", label: "Alaska" },
    { value: "az", label: "Arizona" },
    { value: "ar", label: "Arkansas" },
    { value: "ca", label: "California" },
    { value: "co", label: "Colorado" },
    { value: "ct", label: "Connecticut" },
    { value: "de", label: "Delaware" },
    { value: "fl", label: "Florida" },
    { value: "ga", label: "Georgia" },
    { value: "hi", label: "Hawaii" },
    { value: "id", label: "Idaho" },
    { value: "il", label: "Illinois" },
    { value: "in", label: "Indiana" },
    { value: "ia", label: "Iowa" },
    { value: "ks", label: "Kansas" },
    { value: "ky", label: "Kentucky" },
    { value: "la", label: "Louisiana" },
    { value: "me", label: "Maine" },
    { value: "md", label: "Maryland" },
    { value: "ma", label: "Massachusetts" },
    { value: "mi", label: "Michigan" },
    { value: "mn", label: "Minnesota" },
    { value: "ms", label: "Mississippi" },
    { value: "mo", label: "Missouri" },
    { value: "mt", label: "Montana" },
    { value: "ne", label: "Nebraska" },
    { value: "nv", label: "Nevada" },
    { value: "nh", label: "New Hampshire" },
    { value: "nj", label: "New Jersey" },
    { value: "nm", label: "New Mexico" },
    { value: "ny", label: "New York" },
    { value: "nc", label: "North Carolina" },
    { value: "nd", label: "North Dakota" },
    { value: "oh", label: "Ohio" },
    { value: "ok", label: "Oklahoma" },
    { value: "or", label: "Oregon" },
    { value: "pa", label: "Pennsylvania" },
    { value: "ri", label: "Rhode Island" },
    { value: "sc", label: "South Carolina" },
    { value: "sd", label: "South Dakota" },
    { value: "tn", label: "Tennessee" },
    { value: "tx", label: "Texas" },
    { value: "ut", label: "Utah" },
    { value: "vt", label: "Vermont" },
    { value: "va", label: "Virginia" },
    { value: "wa", label: "Washington" },
    { value: "wv", label: "West Virginia" },
    { value: "wi", label: "Wisconsin" },
    { value: "wy", label: "Wyoming" },
    { value: "dc", label: "District of Columbia" },
  ],
  ca: [
    { value: "ab", label: "Alberta" },
    { value: "bc", label: "British Columbia" },
    { value: "mb", label: "Manitoba" },
    { value: "nb", label: "New Brunswick" },
    { value: "nl", label: "Newfoundland and Labrador" },
    { value: "ns", label: "Nova Scotia" },
    { value: "nt", label: "Northwest Territories" },
    { value: "nu", label: "Nunavut" },
    { value: "on", label: "Ontario" },
    { value: "pe", label: "Prince Edward Island" },
    { value: "qc", label: "Quebec" },
    { value: "sk", label: "Saskatchewan" },
    { value: "yt", label: "Yukon" },
  ],
  uk: [
    { value: "eng", label: "England" },
    { value: "sct", label: "Scotland" },
    { value: "wls", label: "Wales" },
    { value: "nir", label: "Northern Ireland" },
  ],
  au: [
    { value: "act", label: "Australian Capital Territory" },
    { value: "nsw", label: "New South Wales" },
    { value: "nt", label: "Northern Territory" },
    { value: "qld", label: "Queensland" },
    { value: "sa", label: "South Australia" },
    { value: "tas", label: "Tasmania" },
    { value: "vic", label: "Victoria" },
    { value: "wa", label: "Western Australia" },
  ],
  in: [
    { value: "ap", label: "Andhra Pradesh" },
    { value: "ar", label: "Arunachal Pradesh" },
    { value: "as", label: "Assam" },
    { value: "br", label: "Bihar" },
    { value: "ct", label: "Chhattisgarh" },
    { value: "ga", label: "Goa" },
    { value: "gj", label: "Gujarat" },
    { value: "hr", label: "Haryana" },
    { value: "hp", label: "Himachal Pradesh" },
    { value: "jk", label: "Jammu and Kashmir" },
    { value: "jh", label: "Jharkhand" },
    { value: "ka", label: "Karnataka" },
    { value: "kl", label: "Kerala" },
    { value: "mp", label: "Madhya Pradesh" },
    { value: "mh", label: "Maharashtra" },
    { value: "mn", label: "Manipur" },
    { value: "ml", label: "Meghalaya" },
    { value: "mz", label: "Mizoram" },
    { value: "nl", label: "Nagaland" },
    { value: "or", label: "Odisha" },
    { value: "pb", label: "Punjab" },
    { value: "rj", label: "Rajasthan" },
    { value: "sk", label: "Sikkim" },
    { value: "tn", label: "Tamil Nadu" },
    { value: "tg", label: "Telangana" },
    { value: "tr", label: "Tripura" },
    { value: "up", label: "Uttar Pradesh" },
    { value: "ut", label: "Uttarakhand" },
    { value: "wb", label: "West Bengal" },
  ],
  mx: [
    { value: "agu", label: "Aguascalientes" },
    { value: "bcn", label: "Baja California" },
    { value: "bcs", label: "Baja California Sur" },
    { value: "cam", label: "Campeche" },
    { value: "chp", label: "Chiapas" },
    { value: "chh", label: "Chihuahua" },
    { value: "coa", label: "Coahuila" },
    { value: "col", label: "Colima" },
    { value: "cdmx", label: "Ciudad de México" },
    { value: "dur", label: "Durango" },
    { value: "gua", label: "Guanajuato" },
    { value: "gro", label: "Guerrero" },
    { value: "hid", label: "Hidalgo" },
    { value: "jal", label: "Jalisco" },
    { value: "mex", label: "México" },
    { value: "mic", label: "Michoacán" },
    { value: "mor", label: "Morelos" },
    { value: "nay", label: "Nayarit" },
    { value: "nle", label: "Nuevo León" },
    { value: "oax", label: "Oaxaca" },
    { value: "pue", label: "Puebla" },
    { value: "que", label: "Querétaro" },
    { value: "roo", label: "Quintana Roo" },
    { value: "slp", label: "San Luis Potosí" },
    { value: "sin", label: "Sinaloa" },
    { value: "son", label: "Sonora" },
    { value: "tab", label: "Tabasco" },
    { value: "tam", label: "Tamaulipas" },
    { value: "tla", label: "Tlaxcala" },
    { value: "ver", label: "Veracruz" },
    { value: "yuc", label: "Yucatán" },
    { value: "zac", label: "Zacatecas" },
  ],
  br: [
    { value: "ac", label: "Acre" },
    { value: "al", label: "Alagoas" },
    { value: "ap", label: "Amapá" },
    { value: "am", label: "Amazonas" },
    { value: "ba", label: "Bahia" },
    { value: "ce", label: "Ceará" },
    { value: "df", label: "Distrito Federal" },
    { value: "es", label: "Espírito Santo" },
    { value: "go", label: "Goiás" },
    { value: "ma", label: "Maranhão" },
    { value: "mt", label: "Mato Grosso" },
    { value: "ms", label: "Mato Grosso do Sul" },
    { value: "mg", label: "Minas Gerais" },
    { value: "pa", label: "Pará" },
    { value: "pb", label: "Paraíba" },
    { value: "pr", label: "Paraná" },
    { value: "pe", label: "Pernambuco" },
    { value: "pi", label: "Piauí" },
    { value: "rj", label: "Rio de Janeiro" },
    { value: "rn", label: "Rio Grande do Norte" },
    { value: "rs", label: "Rio Grande do Sul" },
    { value: "ro", label: "Rondônia" },
    { value: "rr", label: "Roraima" },
    { value: "sc", label: "Santa Catarina" },
    { value: "sp", label: "São Paulo" },
    { value: "se", label: "Sergipe" },
    { value: "to", label: "Tocantins" },
  ],
  // Add more countries as needed
}

// Function to get states by country code
export function getStatesByCountry(countryCode: string): Array<{ value: string; label: string }> {
  return states[countryCode] || []
}
